// Mocks generated by Mockito 5.4.2 from annotations
// in marvel/test/test_helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i5;
import 'package:marvel/app/model/details/comic_detail_model.dart' as _i11;
import 'package:marvel/app/model/details/event_detail_model.dart' as _i12;
import 'package:marvel/app/model/details/serie_detail_model.dart' as _i13;
import 'package:marvel/app/model/response/character_response_model.dart' as _i9;
import 'package:marvel/app/model/response/detail_response_model.dart' as _i10;
import 'package:marvel/app/repositories/implementation/marvel_repository_impl.dart'
    as _i6;
import 'package:marvel/core/enviroment/env.dart' as _i2;
import 'package:marvel/core/exceptions/custom.exceptions.dart' as _i8;
import 'package:marvel/core/services/network/http.service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEnvironment_0 extends _i1.SmartFake implements _i2.Environment {
  _FakeEnvironment_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpService_1 extends _i1.SmartFake implements _i3.HttpService {
  _FakeHttpService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i5.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MarvelRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarvelRepositoryImpl extends _i1.Mock
    implements _i6.MarvelRepositoryImpl {
  MockMarvelRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Environment get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _FakeEnvironment_0(
          this,
          Invocation.getter(#env),
        ),
      ) as _i2.Environment);
  @override
  _i3.HttpService get httpService => (super.noSuchMethod(
        Invocation.getter(#httpService),
        returnValue: _FakeHttpService_1(
          this,
          Invocation.getter(#httpService),
        ),
      ) as _i3.HttpService);
  @override
  _i7.Future<_i4.Either<_i8.CustomException, _i9.CharacterResponse>>
      getCharacters() => (super.noSuchMethod(
            Invocation.method(
              #getCharacters,
              [],
            ),
            returnValue: _i7.Future<
                    _i4.Either<_i8.CustomException,
                        _i9.CharacterResponse>>.value(
                _FakeEither_2<_i8.CustomException, _i9.CharacterResponse>(
              this,
              Invocation.method(
                #getCharacters,
                [],
              ),
            )),
          ) as _i7
              .Future<_i4.Either<_i8.CustomException, _i9.CharacterResponse>>);
  @override
  _i7.Future<
          _i4.Either<_i8.CustomException,
              _i10.DetailResponse<_i11.ComicDetail>>>
      getComics({required int? id}) => (super.noSuchMethod(
            Invocation.method(
              #getComics,
              [],
              {#id: id},
            ),
            returnValue: _i7.Future<
                _i4.Either<_i8.CustomException,
                    _i10.DetailResponse<_i11.ComicDetail>>>.value(_FakeEither_2<
                _i8.CustomException, _i10.DetailResponse<_i11.ComicDetail>>(
              this,
              Invocation.method(
                #getComics,
                [],
                {#id: id},
              ),
            )),
          ) as _i7.Future<
              _i4.Either<_i8.CustomException,
                  _i10.DetailResponse<_i11.ComicDetail>>>);
  @override
  _i7.Future<
          _i4.Either<_i8.CustomException,
              _i10.DetailResponse<_i12.EventDetail>>>
      getEvents({required int? id}) => (super.noSuchMethod(
            Invocation.method(
              #getEvents,
              [],
              {#id: id},
            ),
            returnValue: _i7.Future<
                _i4.Either<_i8.CustomException,
                    _i10.DetailResponse<_i12.EventDetail>>>.value(_FakeEither_2<
                _i8.CustomException, _i10.DetailResponse<_i12.EventDetail>>(
              this,
              Invocation.method(
                #getEvents,
                [],
                {#id: id},
              ),
            )),
          ) as _i7.Future<
              _i4.Either<_i8.CustomException,
                  _i10.DetailResponse<_i12.EventDetail>>>);
  @override
  _i7.Future<
          _i4.Either<_i8.CustomException,
              _i10.DetailResponse<_i13.SerieDetail>>>
      getSeries({required int? id}) => (super.noSuchMethod(
            Invocation.method(
              #getSeries,
              [],
              {#id: id},
            ),
            returnValue: _i7.Future<
                _i4.Either<_i8.CustomException,
                    _i10.DetailResponse<_i13.SerieDetail>>>.value(_FakeEither_2<
                _i8.CustomException, _i10.DetailResponse<_i13.SerieDetail>>(
              this,
              Invocation.method(
                #getSeries,
                [],
                {#id: id},
              ),
            )),
          ) as _i7.Future<
              _i4.Either<_i8.CustomException,
                  _i10.DetailResponse<_i13.SerieDetail>>>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.HttpService {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set interceptors(List<_i5.Interceptor>? _interceptors) => super.noSuchMethod(
        Invocation.setter(
          #interceptors,
          _interceptors,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i5.Response<dynamic>> get(
    String? uri, {
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [uri],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [uri],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> post(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> delete(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #delete,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> patch(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #patch,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> put(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #put,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
}
